version: "3"
services:
  db:
    build:
      dockerfile: Dockerfile
    container_name: postgis
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: postgis
      POSTGRES_PASSWORD: postgis
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgis@example.com
      PGADMIN_DEFAULT_PASSWORD: postgis
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data: